# Generated by Django 3.2 on 2021-04-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255, null=True, verbose_name='Бренд'),
        ),
        migrations.DeleteModel(
            name='Spec',
        ),
    ]
