# Generated by Django 3.2 on 2021-04-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_cart_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='all_price',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=9, verbose_name='Вся сума'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сума із знижкою'),
        ),
    ]
