# Generated by Django 3.2 on 2021-04-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210424_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='all_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
    ]
