# Generated by Django 3.2 on 2021-04-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210424_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='all_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Вся сума'),
        ),
    ]
