# Generated by Django 3.2 on 2021-04-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_cart_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
    ]
