# Generated by Django 3.2 on 2021-04-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_cart_all_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='all_product',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
