# Generated by Django 3.2 on 2021-05-21 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20210520_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='product.product'),
        ),
    ]
