# Generated by Django 3.2 on 2021-05-21 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_spec_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortimgproduct',
            name='mdl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_product', to='product.product'),
        ),
    ]
