# Generated by Django 3.2 on 2021-04-18 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 12, 23, 15, 186018, tzinfo=utc), verbose_name='Дата на виконання'),
        ),
    ]
