# Generated by Django 3.2 on 2021-05-20 17:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 20, 17, 0, 50, 923600, tzinfo=utc), verbose_name='Дата на виконання'),
        ),
    ]
